Name: product.rpc
ListenOn: 0.0.0.0:8080
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc

DataSource: root:root@tcp(127.0.0.1:3306)/dcs?charset=utf8&parseTime=True&loc=Local

Cache:
  - Host: localhost:6379

Redis:
  #  Key: rpc:auth:user     # 指定 Key 应为 hash 类型
  Host: localhost:6379