// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"dcs/rpc/product/internal/logic"
	"dcs/rpc/product/internal/svc"
	"dcs/rpc/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) GetProduct(ctx context.Context, in *product.DetailReq) (*product.ProductDetail, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}
