// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"dcs/rpc/order/internal/logic"
	"dcs/rpc/order/internal/svc"
	"dcs/rpc/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Create(ctx context.Context, in *order.CreateOrderReq) (*order.CreateOrderResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
