// Code generated by goctl. DO NOT EDIT.
// Source: producer.proto

package server

import (
	"context"

	"dcs/rpc/producer/internal/logic"
	"dcs/rpc/producer/internal/svc"
	"dcs/rpc/producer/producer"
)

type ProducerServer struct {
	svcCtx *svc.ServiceContext
	producer.UnimplementedProducerServer
}

func NewProducerServer(svcCtx *svc.ServiceContext) *ProducerServer {
	return &ProducerServer{
		svcCtx: svcCtx,
	}
}

func (s *ProducerServer) Publish(ctx context.Context, in *producer.Request) (*producer.Response, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}
